// Auto-generated by scripts/optimize-images.mts — do not edit manually

export interface ImageData {
    blur: string
    srcSet: string
    src: string
    width: number
    height: number
}

export const imageManifest: Record<string, ImageData> = {
    '2S8A6428': {
        blur: 'data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAAAwBQCdASoUAB4APu1qq1EppaOiqAqpMB2JZwAAj/e7cznuMASVjP7NzKlHE7dJIEVJ4AD+5yG60OwcOU1mLOZyD0cAD54N412sx7kDMj2Ukm/FxR41hmRU9o3ftdMD9ss0kAtvXeaSEQPvTjAcwprm5XKO2BteFlgr+b7gBBQNCgAA',
        srcSet: '/images/2S8A6428/2S8A6428-320w.webp 320w, /images/2S8A6428/2S8A6428-640w.webp 640w, /images/2S8A6428/2S8A6428-960w.webp 960w, /images/2S8A6428/2S8A6428-1280w.webp 1280w',
        src: '/images/2S8A6428/2S8A6428-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6445': {
        blur: 'data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwBACdASoUAB4APu1kq06ppaQiKA1RMB2JZwAAve92DrRSkd5H6/PvnqpMuni4AP7qgp/W2AFq0THs0/wW9cPrtBvhSHSS3u+EDb+AnHMIEp4DUL9b4JsTBf/wxV5CyUAJF5OtqXxOhvWEF3kJaxziiJWCwwN28CQN4F1vRMAAAA==',
        srcSet: '/images/2S8A6445/2S8A6445-320w.webp 320w, /images/2S8A6445/2S8A6445-640w.webp 640w, /images/2S8A6445/2S8A6445-960w.webp 960w, /images/2S8A6445/2S8A6445-1280w.webp 1280w',
        src: '/images/2S8A6445/2S8A6445-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6480': {
        blur: 'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAwBQCdASoUAB4APuFUpU2opCOiN/qoARAcCWUAAFu0G4YqEnrw3tTCYv6HG1sfBM7HAAD+6nahvggpMVXceZE/N+txOU4BuazIQtmtbbaa2c5E179cNXRVF/yV1r0TVGnY8ewkOJmSOSZ+wlsogM9wOVH/ixVLulOEvAJekGwrL4v/GCe7eDl6kIAAAA==',
        srcSet: '/images/2S8A6480/2S8A6480-320w.webp 320w, /images/2S8A6480/2S8A6480-640w.webp 640w, /images/2S8A6480/2S8A6480-960w.webp 960w, /images/2S8A6480/2S8A6480-1280w.webp 1280w',
        src: '/images/2S8A6480/2S8A6480-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6494': {
        blur: 'data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAABQBQCdASoUAB4APu1mq0+ppSOiMBgIATAdiWUAwcwOJkLsN1LSs8Nx6jxoZCbMaAeHIAAA/u1hfynEfnvTa5u8+OzQBS+KT8nucsNiPQvwm0xp7rndNK/j2ZYftubRuxHSLBkNTbQ1OW8cwB7NacqQELUCpY/WvTBRxHSduoVhJaTyGnsmR7A9rZCAvUXe1sWFOZV9D/8kwgzNeJ1h6IxT59hP4Y4owVMTZBm1TT0A/KyQGnhP2+CejcAAAA==',
        srcSet: '/images/2S8A6494/2S8A6494-320w.webp 320w, /images/2S8A6494/2S8A6494-640w.webp 640w, /images/2S8A6494/2S8A6494-960w.webp 960w, /images/2S8A6494/2S8A6494-1280w.webp 1280w',
        src: '/images/2S8A6494/2S8A6494-1280w.webp',
        width: 5422,
        height: 8128,
    },
    '2S8A6514': {
        blur: 'data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACwBACdASoUAB4APu1qrU+ppiQiMBgIATAdiWcAAI9343T6RjHiNatHfXFOM+w4AP7TTFePgZmdycTEMY32jj2mpcQTKxeUmJ/OotnWRVRkDsOEPBMMHU2hrkGAYOItQ8V5dcNRYWGVoiHqPv+35iQAAAA=',
        srcSet: '/images/2S8A6514/2S8A6514-320w.webp 320w, /images/2S8A6514/2S8A6514-640w.webp 640w, /images/2S8A6514/2S8A6514-960w.webp 960w, /images/2S8A6514/2S8A6514-1280w.webp 1280w',
        src: '/images/2S8A6514/2S8A6514-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6544': {
        blur: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACQBACdASoUAB4APu1gq02ppSQiMBgMATAdiWUAzFgMG3FwaKC6i2TzuqcNnQAA/vAGnj5puoNbo+SQXZW2/JGF/vWK4vaAoi6xvWt9mZJueWHQSjZJvi7aFBX6yWbfh4Y9OIERZ2l3fp9M+HkptUeWQILLEzrv+67SJrQ4AAA=',
        srcSet: '/images/2S8A6544/2S8A6544-320w.webp 320w, /images/2S8A6544/2S8A6544-640w.webp 640w, /images/2S8A6544/2S8A6544-960w.webp 960w, /images/2S8A6544/2S8A6544-1280w.webp 1280w',
        src: '/images/2S8A6544/2S8A6544-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6566': {
        blur: 'data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQBACdASoUAB4APu1iqU2ppaOiMAgBMB2JYwDLLCHgCmEcZRE1NvIUNozCQkdgAAD+5x1bsZSOO4akG9UrL5v0fQNtdHwrzjF8zJNWDDH+cwDA1Rt+ZgQUYBIQwESjFr7ghGqJwBbOzkgRFgYPXA7C6B79D+1cMKKEG3xbll++nnpoUcCmfKKgAAA=',
        srcSet: '/images/2S8A6566/2S8A6566-320w.webp 320w, /images/2S8A6566/2S8A6566-640w.webp 640w, /images/2S8A6566/2S8A6566-960w.webp 960w, /images/2S8A6566/2S8A6566-1280w.webp 1280w',
        src: '/images/2S8A6566/2S8A6566-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6575': {
        blur: 'data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABQBACdASoUAB4APu1qrVEppaQnKAqpMB2JYwC+SAyp7lcR7av3VCA4ita8AP7n7OpIxhO498dgQc1hNpy73+Ha5RKPGFzL8jREXX8vYtVZbS24cogxFg0P2O9hCPl+/iDWUHyFUqhCHXzhqY/k74np6JaFgyeFqTpdBCdKN4YPb4E578vPh8nJL2Ss9vjK3QWp+IG278qoAAAA',
        srcSet: '/images/2S8A6575/2S8A6575-320w.webp 320w, /images/2S8A6575/2S8A6575-640w.webp 640w, /images/2S8A6575/2S8A6575-960w.webp 960w, /images/2S8A6575/2S8A6575-1280w.webp 1280w',
        src: '/images/2S8A6575/2S8A6575-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6578': {
        blur: 'data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAADQBACdASoUAB4APu1or1AppaSiqAqpMB2JYwC+SAxUYmsn5p+9XtIIPUuZSg0oAAD+5+CHp3LWC8bb/ISsQmGRFk8OG3/ekE8RoVfsaoxwjxITMQIB8s9k6ZSM75PVG96ghpW8B1UU6vapT46wSEjvz1jZ0EwyDQXeYb9FCtHlsfRatHXjnxMBmJuOPdOF+mBb3JG/y4StCs8qKUQO5gAA',
        srcSet: '/images/2S8A6578/2S8A6578-320w.webp 320w, /images/2S8A6578/2S8A6578-640w.webp 640w, /images/2S8A6578/2S8A6578-960w.webp 960w, /images/2S8A6578/2S8A6578-1280w.webp 1280w',
        src: '/images/2S8A6578/2S8A6578-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6598': {
        blur: 'data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAwBACdASoUAB4APu1oq08ppiOiMBgIATAdiWcA0BgIHATcaxi9v0vIyAAA/e1m9cqo6eE9JQQis8qUPpQCgwvIEVoMuV5mO95UzxMy96AVhIx9N2M3/cfG/rXVhpGVhp1EfBEW+3szzlDF4n6Ukyxa8MWS7dwhABknkAJaHP254DqDOAAAAA==',
        srcSet: '/images/2S8A6598/2S8A6598-320w.webp 320w, /images/2S8A6598/2S8A6598-640w.webp 640w, /images/2S8A6598/2S8A6598-960w.webp 960w, /images/2S8A6598/2S8A6598-1280w.webp 1280w',
        src: '/images/2S8A6598/2S8A6598-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6626': {
        blur: 'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAwCdASoUAB4APu1osFAppaSiqAqpMB2JZwAAH5F9+RLxRmzEX/SgAP6zNYBr4/P7KJv55r7K898TmxnGztNQVRSxKo6X46ENVPMffUzyyVYvnyXz2lZ9G9kFoOKuRncAAA==',
        srcSet: '/images/2S8A6626/2S8A6626-320w.webp 320w, /images/2S8A6626/2S8A6626-640w.webp 640w, /images/2S8A6626/2S8A6626-960w.webp 960w, /images/2S8A6626/2S8A6626-1280w.webp 1280w',
        src: '/images/2S8A6626/2S8A6626-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6663': {
        blur: 'data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAADwBACdASoUAB4APu1iqE2ppaOiMAgBMB2JQBhQMYTav8Ji9YWj4+pL14L0m01ZI3gA/t+zs9WMNKGWV+kxwQdEXMlEWPtHSLcC4sso65KSg6amq250yr8o1xc/NTeeYYHtxuuw+DFIAG7iZxFRg/VIGdWUbujmpPIR8v/FOfn7z0qXg35SR4a5us2Dures4cHyR4dXhesGd3k9mdJmQAAA',
        srcSet: '/images/2S8A6663/2S8A6663-320w.webp 320w, /images/2S8A6663/2S8A6663-640w.webp 640w, /images/2S8A6663/2S8A6663-960w.webp 960w, /images/2S8A6663/2S8A6663-1280w.webp 1280w',
        src: '/images/2S8A6663/2S8A6663-1280w.webp',
        width: 5340,
        height: 8006,
    },
    '2S8A6676': {
        blur: 'data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAACQBQCdASoUAB4APu1iqE2ppaOiMAgBMB2JZwDH5y6BYr5xcck1tBzCR+o8cOal9O8IoowssADOG7JrP0L4cJhV4kYnUp15FZtUzX9FCpCOjdXhjNHoqAHW7yGs0ro4skPxG2LyyIGVsuuJ0UiiLCKPk99+2dRJOIVEtV1ZfU+ifnZ6Q1M0UR1aiSEmsgzFSkcF5z5wjG7j+dsjAAoI9727Jn/l8H2cKNxjCwdRanFr3nODsgOmSI1TJN0Uh3Ssl48Hr4MR3rdQAA==',
        srcSet: '/images/2S8A6676/2S8A6676-320w.webp 320w, /images/2S8A6676/2S8A6676-640w.webp 640w, /images/2S8A6676/2S8A6676-960w.webp 960w, /images/2S8A6676/2S8A6676-1280w.webp 1280w',
        src: '/images/2S8A6676/2S8A6676-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6682': {
        blur: 'data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAAAwBQCdASoUAB4APu1kq1AppSOisBgIATAdiWcAxzAygzCIca+rAbOJ2oo5AgrJpvPQAAD+9Aq4AunEV/iNML0j/mLrSUx2A0pT+SgPkIYoYM7sdXUvyn8+fm8l6y1w7pAZZ7rbNuxaWCAFiMlVp3LjOoOiKNvEPbkBWAFJu1I4xVz9G13DiFsCJixYsIPIMT2oHTkWzERX6fLaVegaB2bYC8cN0ThK1nvb7XF6JW8NoyFhYzdfJ+mAAAA=',
        srcSet: '/images/2S8A6682/2S8A6682-320w.webp 320w, /images/2S8A6682/2S8A6682-640w.webp 640w, /images/2S8A6682/2S8A6682-960w.webp 960w, /images/2S8A6682/2S8A6682-1280w.webp 1280w',
        src: '/images/2S8A6682/2S8A6682-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6687': {
        blur: 'data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAACQBACdASoUAB4APu1kqU2ppaOiMAgBMB2JZwDPZywBt3FyAohHSo00WBrNSAAA/vHcpgRFYVgwT22OkewJ0aH39TWbnhD6uIUvXEao4OszoSni5IdZqmbrKo050GOyCiyVeaO01EZY9VDl878HlITXPYR3B2xnlGJXzdOZC3FfjuOv3lhlEcUfshcei7s3+Ff0rVFUUq/gi6PKycBlky4h92ZFrt20jxqAAA==',
        srcSet: '/images/2S8A6687/2S8A6687-320w.webp 320w, /images/2S8A6687/2S8A6687-640w.webp 640w, /images/2S8A6687/2S8A6687-960w.webp 960w, /images/2S8A6687/2S8A6687-1280w.webp 1280w',
        src: '/images/2S8A6687/2S8A6687-1280w.webp',
        width: 5464,
        height: 8192,
    },
    'Z72_5967': {
        blur: 'data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACQBQCdASoUAB4APuVgpE2pJaMiMAwBIByJZQC+SdwLhUZMyMjnYWZP4zz50EOLjZJBAPo+AAD+3S3bjZj3813spptpayZVCnCwdAmryj6Mm5uGjDBYjBuOAqwFhluP44vFBA96I4Y3Z0tJ6qd/6iQzFyprjqeXqvIiupRk2vos4w/kIl9CD1v8ARP2XtFJ4tWbcHtZcUmgszb+6kqDISibxeJcJADFfGE6ztiAAAA=',
        srcSet: '/images/Z72_5967/Z72_5967-320w.webp 320w, /images/Z72_5967/Z72_5967-640w.webp 640w, /images/Z72_5967/Z72_5967-960w.webp 960w, /images/Z72_5967/Z72_5967-1280w.webp 1280w',
        src: '/images/Z72_5967/Z72_5967-1280w.webp',
        width: 5504,
        height: 8256,
    },
    'Z72_6163': {
        blur: 'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwBACdASoUAB4APu1mpU2ppaMiMBgMATAdiWkAzfwQ75fQ1HSU4toSBJAV9lFeloAA/tWN71oNaORzmOcLHjsnrArtIEhISDrdjqptXfpoaQYVGikZkHQA',
        srcSet: '/images/Z72_6163/Z72_6163-320w.webp 320w, /images/Z72_6163/Z72_6163-640w.webp 640w, /images/Z72_6163/Z72_6163-960w.webp 960w, /images/Z72_6163/Z72_6163-1280w.webp 1280w',
        src: '/images/Z72_6163/Z72_6163-1280w.webp',
        width: 5333,
        height: 7999,
    },
    'Z72_6221': {
        blur: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADQBACdASoUAB4APu1mqU4ppaOiMAgBMB2JZwAAUqUaJVWeLklu2hec9b5TN52QoAD+4TwCTuNK50Lra8NOxFLSUqUVUitZq2JJWnzUzh431ixxmyChLoSuknr/INdysbin42efcd28PxSvsIxwCzWnzH6Eioli7b8niAjMBAA=',
        srcSet: '/images/Z72_6221/Z72_6221-320w.webp 320w, /images/Z72_6221/Z72_6221-640w.webp 640w, /images/Z72_6221/Z72_6221-960w.webp 960w, /images/Z72_6221/Z72_6221-1280w.webp 1280w',
        src: '/images/Z72_6221/Z72_6221-1280w.webp',
        width: 5504,
        height: 8256,
    },
    'Z72_6229': {
        blur: 'data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBQCdASoUAB4APu1or1CppaSiqAqpMB2JZwAD4/M4/hVlQaMAqgNp3Q08Jxh5p/hadzwA/rFfqho8i+71cX2qelX2Xw01a4JvmO8VLumw0xSESs18wYe85CCBRdOxJd8jIEZOITbjb6IsRDIrXrfNAH8O6K567WjdgE4Ogu1pr/n8gWlabAAA',
        srcSet: '/images/Z72_6229/Z72_6229-320w.webp 320w, /images/Z72_6229/Z72_6229-640w.webp 640w, /images/Z72_6229/Z72_6229-960w.webp 960w, /images/Z72_6229/Z72_6229-1280w.webp 1280w',
        src: '/images/Z72_6229/Z72_6229-1280w.webp',
        width: 5504,
        height: 8256,
    },
    'hero-couple': {
        blur: 'data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABQBACdASoUAB4APu1irE+ppSQiMBgIATAdiWUAwNwIG0dBmpw4Kb2OojhgAPgwjZMfo9spRCd53g++6TPDF8CQTaUmnFgxU6w/MlyY2elJiFuwkiGGTxU+u0znx4N10DdOQ4KsGXSQYKXG1KNQMP4biPhQo9/KfWr90DTJVJwGbaPP5ZjqFdoAAAA=',
        srcSet: '/images/hero-couple/hero-couple-320w.webp 320w, /images/hero-couple/hero-couple-640w.webp 640w, /images/hero-couple/hero-couple-960w.webp 960w, /images/hero-couple/hero-couple-1280w.webp 1280w',
        src: '/images/hero-couple/hero-couple-1280w.webp',
        width: 5464,
        height: 8192,
    },
}
