// Auto-generated by scripts/optimize-images.mts — do not edit manually

export interface ImageData {
    blur: string
    srcSet: string
    src: string
    width: number
    height: number
}

export const imageManifest: Record<string, ImageData> = {
    '2S8A6480': {
        blur: 'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAwBQCdASoUAB4APuFUpU2opCOiN/qoARAcCWUAAFu0G4YqEnrw3tTCYv6HG1sfBM7HAAD+6nahvggpMVXceZE/N+txOU4BuazIQtmtbbaa2c5E179cNXRVF/yV1r0TVGnY8ewkOJmSOSZ+wlsogM9wOVH/ixVLulOEvAJekGwrL4v/GCe7eDl6kIAAAA==',
        srcSet: '/images/2S8A6480/2S8A6480-320w.webp 320w, /images/2S8A6480/2S8A6480-640w.webp 640w, /images/2S8A6480/2S8A6480-960w.webp 960w, /images/2S8A6480/2S8A6480-1280w.webp 1280w',
        src: '/images/2S8A6480/2S8A6480-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6575': {
        blur: 'data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABQBACdASoUAB4APu1qrVEppaQnKAqpMB2JYwC+SAyp7lcR7av3VCA4ita8AP7n7OpIxhO498dgQc1hNpy73+Ha5RKPGFzL8jREXX8vYtVZbS24cogxFg0P2O9hCPl+/iDWUHyFUqhCHXzhqY/k74np6JaFgyeFqTpdBCdKN4YPb4E578vPh8nJL2Ss9vjK3QWp+IG278qoAAAA',
        srcSet: '/images/2S8A6575/2S8A6575-320w.webp 320w, /images/2S8A6575/2S8A6575-640w.webp 640w, /images/2S8A6575/2S8A6575-960w.webp 960w, /images/2S8A6575/2S8A6575-1280w.webp 1280w',
        src: '/images/2S8A6575/2S8A6575-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6578': {
        blur: 'data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAADQBACdASoUAB4APu1or1AppaSiqAqpMB2JYwC+SAxUYmsn5p+9XtIIPUuZSg0oAAD+5+CHp3LWC8bb/ISsQmGRFk8OG3/ekE8RoVfsaoxwjxITMQIB8s9k6ZSM75PVG96ghpW8B1UU6vapT46wSEjvz1jZ0EwyDQXeYb9FCtHlsfRatHXjnxMBmJuOPdOF+mBb3JG/y4StCs8qKUQO5gAA',
        srcSet: '/images/2S8A6578/2S8A6578-320w.webp 320w, /images/2S8A6578/2S8A6578-640w.webp 640w, /images/2S8A6578/2S8A6578-960w.webp 960w, /images/2S8A6578/2S8A6578-1280w.webp 1280w',
        src: '/images/2S8A6578/2S8A6578-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6676': {
        blur: 'data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAACQBQCdASoUAB4APu1iqE2ppaOiMAgBMB2JZwDH5y6BYr5xcck1tBzCR+o8cOal9O8IoowssADOG7JrP0L4cJhV4kYnUp15FZtUzX9FCpCOjdXhjNHoqAHW7yGs0ro4skPxG2LyyIGVsuuJ0UiiLCKPk99+2dRJOIVEtV1ZfU+ifnZ6Q1M0UR1aiSEmsgzFSkcF5z5wjG7j+dsjAAoI9727Jn/l8H2cKNxjCwdRanFr3nODsgOmSI1TJN0Uh3Ssl48Hr4MR3rdQAA==',
        srcSet: '/images/2S8A6676/2S8A6676-320w.webp 320w, /images/2S8A6676/2S8A6676-640w.webp 640w, /images/2S8A6676/2S8A6676-960w.webp 960w, /images/2S8A6676/2S8A6676-1280w.webp 1280w',
        src: '/images/2S8A6676/2S8A6676-1280w.webp',
        width: 5464,
        height: 8192,
    },
    '2S8A6682': {
        blur: 'data:image/webp;base64,UklGRsYAAABXRUJQVlA4ILoAAAAwBQCdASoUAB4APu1kq1AppSOisBgIATAdiWcAxzAygzCIca+rAbOJ2oo5AgrJpvPQAAD+9Aq4AunEV/iNML0j/mLrSUx2A0pT+SgPkIYoYM7sdXUvyn8+fm8l6y1w7pAZZ7rbNuxaWCAFiMlVp3LjOoOiKNvEPbkBWAFJu1I4xVz9G13DiFsCJixYsIPIMT2oHTkWzERX6fLaVegaB2bYC8cN0ThK1nvb7XF6JW8NoyFhYzdfJ+mAAAA=',
        srcSet: '/images/2S8A6682/2S8A6682-320w.webp 320w, /images/2S8A6682/2S8A6682-640w.webp 640w, /images/2S8A6682/2S8A6682-960w.webp 960w, /images/2S8A6682/2S8A6682-1280w.webp 1280w',
        src: '/images/2S8A6682/2S8A6682-1280w.webp',
        width: 5464,
        height: 8192,
    },
    'Z72_6163': {
        blur: 'data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwBACdASoUAB4APu1mpU2ppaMiMBgMATAdiWkAzfwQ75fQ1HSU4toSBJAV9lFeloAA/tWN71oNaORzmOcLHjsnrArtIEhISDrdjqptXfpoaQYVGikZkHQA',
        srcSet: '/images/Z72_6163/Z72_6163-320w.webp 320w, /images/Z72_6163/Z72_6163-640w.webp 640w, /images/Z72_6163/Z72_6163-960w.webp 960w, /images/Z72_6163/Z72_6163-1280w.webp 1280w',
        src: '/images/Z72_6163/Z72_6163-1280w.webp',
        width: 5333,
        height: 7999,
    },
    'Z72_6221': {
        blur: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADQBACdASoUAB4APu1mqU4ppaOiMAgBMB2JZwAAUqUaJVWeLklu2hec9b5TN52QoAD+4TwCTuNK50Lra8NOxFLSUqUVUitZq2JJWnzUzh431ixxmyChLoSuknr/INdysbin42efcd28PxSvsIxwCzWnzH6Eioli7b8niAjMBAA=',
        srcSet: '/images/Z72_6221/Z72_6221-320w.webp 320w, /images/Z72_6221/Z72_6221-640w.webp 640w, /images/Z72_6221/Z72_6221-960w.webp 960w, /images/Z72_6221/Z72_6221-1280w.webp 1280w',
        src: '/images/Z72_6221/Z72_6221-1280w.webp',
        width: 5504,
        height: 8256,
    },
    'hero-couple': {
        blur: 'data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABQBACdASoUAB4APu1irE+ppSQiMBgIATAdiWUAwNwIG0dBmpw4Kb2OojhgAPgwjZMfo9spRCd53g++6TPDF8CQTaUmnFgxU6w/MlyY2elJiFuwkiGGTxU+u0znx4N10DdOQ4KsGXSQYKXG1KNQMP4biPhQo9/KfWr90DTJVJwGbaPP5ZjqFdoAAAA=',
        srcSet: '/images/hero-couple/hero-couple-320w.webp 320w, /images/hero-couple/hero-couple-640w.webp 640w, /images/hero-couple/hero-couple-960w.webp 960w, /images/hero-couple/hero-couple-1280w.webp 1280w',
        src: '/images/hero-couple/hero-couple-1280w.webp',
        width: 5464,
        height: 8192,
    },
}
