import sharp from 'sharp'
import { readdir, mkdir, writeFile } from 'node:fs/promises'
import { join, parse } from 'node:path'

const SRC_DIR = join(import.meta.dirname, '..', 'src', 'assets', 'wedding-images')
const OUT_DIR = join(import.meta.dirname, '..', 'public', 'images')
const MANIFEST_PATH = join(
    import.meta.dirname,
    '..',
    'src',
    'app',
    'components',
    'image-manifest.ts',
)

const VARIANTS = [
    { suffix: 'sm', width: 320, quality: 80 },
    { suffix: 'md', width: 640, quality: 80 },
    { suffix: 'lg', width: 960, quality: 82 },
    { suffix: 'xl', width: 1280, quality: 85 },
] as const

const BLUR_WIDTH = 20

interface ImageEntry {
    key: string
    blur: string
    width: number
    height: number
}

async function main() {
    const files = (await readdir(SRC_DIR)).filter((f) => /\.(jpg|jpeg|png)$/i.test(f))
    console.log(`Found ${files.length} images`)

    const entries: ImageEntry[] = []

    for (const file of files) {
        const { name } = parse(file)
        const srcPath = join(SRC_DIR, file)
        const outSubDir = join(OUT_DIR, name)
        await mkdir(outSubDir, { recursive: true })

        const image = sharp(srcPath)
        const meta = await image.metadata()
        const origW = meta.width!
        const origH = meta.height!

        // Generate WebP variants
        for (const { suffix, width, quality } of VARIANTS) {
            const outPath = join(outSubDir, `${name}-${width}w.webp`)
            await sharp(srcPath).resize(width).webp({ quality }).toFile(outPath)
            console.log(`  ${name}-${width}w.webp`)
        }

        // Generate blur placeholder
        const blurBuf = await sharp(srcPath)
            .resize(BLUR_WIDTH)
            .webp({ quality: 40 })
            .toBuffer()
        const blur = `data:image/webp;base64,${blurBuf.toString('base64')}`

        entries.push({ key: name, blur, width: origW, height: origH })
    }

    // Generate manifest
    const lines = [
        '// Auto-generated by scripts/optimize-images.mts — do not edit manually',
        '',
        'export interface ImageData {',
        '    blur: string',
        '    srcSet: string',
        '    src: string',
        '    width: number',
        '    height: number',
        '}',
        '',
        'export const imageManifest: Record<string, ImageData> = {',
    ]

    for (const { key, blur, width, height } of entries) {
        const srcSet = VARIANTS.map((v) => `/images/${key}/${key}-${v.width}w.webp ${v.width}w`).join(
            ', ',
        )
        const src = `/images/${key}/${key}-${VARIANTS[VARIANTS.length - 1].width}w.webp`
        lines.push(`    '${key}': {`)
        lines.push(`        blur: '${blur}',`)
        lines.push(`        srcSet: '${srcSet}',`)
        lines.push(`        src: '${src}',`)
        lines.push(`        width: ${width},`)
        lines.push(`        height: ${height},`)
        lines.push(`    },`)
    }

    lines.push('}')
    lines.push('')

    await writeFile(MANIFEST_PATH, lines.join('\n'))
    console.log(`\nManifest written to ${MANIFEST_PATH}`)
    console.log(`Done! ${entries.length} images optimized.`)
}

main().catch((err) => {
    console.error(err)
    process.exit(1)
})
